### PR TITLE
Broadcast & Rooms support added back

### PR DESCRIPTION
**Pull request by kunaldawn**
## Adds following api to Server
```
// JoinRoom joins given connection to the room
JoinRoom(room string, connection Conn)

// LeaveRoom leaves given connection from the room
LeaveRoom(room string, connection Conn)

// LeaveAllRooms leaves the given connection from all rooms
LeaveAllRooms(connection Conn)

// ClearRoom clears the room
ClearRoom(room string)

// BroadcastToRoom broadcasts given event & args to all the connections in the room
BroadcastToRoom(room, event string, args ...interface{}) 

// RoomLen gives number of connections in the room
RoomLen(room string) int

//  Rooms gives list of all the rooms
Rooms() []string
```

## Adds following api to Conn
```
Join(room string)
Leave(room string)
LeaveAll()
Rooms() []string
```

### CODE REVIEW

**Comment by kunaldawn** [comment]
ZZZ ?

**Comment by ciazhar** [comment]
please

**Comment by zishang520** [comment]
🙃Flowers are withered...

**Comment by josealvaradoo** [comment]
Hey! Can you merge it plase? 🙏

**Comment by googollee** [comment]
I think it lacks ut. As it looks good and users require it, merged. Thanks.

**Comment by josealvaradoo** [comment]
Thank you @googollee

**Comment by jura-b** [comment]
> I think it lacks ut. As it looks good and users require it, merged. Thanks.

Could you tag this version?

**Comment by erkie** [comment]
If this is not yet done I’ll make sure it gets done tomorrow

**Comment by erkie** [comment]
@jura-b I created the tag  `v1.4.2`

**Pull request merged**
