### PR TITLE
WIP: Deadlock on multiple Emit's

### PR DESCRIPTION
**Pull request by erkie**
This is a WIP branch so the progress and work can be shared among more people.

- [x] Change order of calling OnConnect handler, and making sure all changes are setup correctly before allowing user to handle socket. This fixes a problem with calling `so.Emit` inside `OnConnect`. The handlers and handshakes were not setup to properly write messages on the socket
- [ ] *NOT FIXED:* Calling `so.Emit` in succession causes a deadlock where the connection dies and a new one is setup

### CODE REVIEW

**Comment by erkie** [comment]
Repro code:

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	socketio "github.com/googollee/go-socket.io"
)

func main() {
	server, err := socketio.NewServer(nil)
	if err != nil {
		log.Fatal(err)
	}

	server.OnConnect("/", func(s socketio.Conn) error {
		s.SetContext("")
		fmt.Println("connected:", s.ID())

		fmt.Println("client: emitting")
		s.Emit("reply", "hello world: "+s.ID())
		fmt.Println("client: emitted hello world " + s.ID())

		fmt.Println("client: foo")
		s.Emit("foo", "bar "+s.ID())
		fmt.Println("client: emitted foo bar")

		return nil
	})

	go server.Serve()
	defer server.Close()

	http.Handle("/socket.io/", server)
	http.Handle("/", http.FileServer(http.Dir("./static")))
	log.Fatal(http.ListenAndServe(":5000", nil))
}
```

`static/index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    test
   <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.js"></script>
   <script type="text/javascript">
    var socket = io()

    socket.on("connect", function() {
      console.log("on connect")
    });
    socket.on("reply", function(msg) {
      console.log("got reply", msg)
    })
    socket.on("foo", function(msg) {
      console.log("got foo", msg)
    })
   </script>
</body>
</html>
```

**Comment by erkie** [comment]
The deadlock happens here:

https://github.com/googollee/go-socket.io/blob/master/parser/encoder.go#L115

The problem might exist in go-engine.io because the `w io.WriteCloser` passed into `func (e *Encoder) writePacket(w io.WriteCloser, h Header, args []interface{}) ([][]byte, error) {` is a `*engineio.writer`

**Comment by erkie** [comment]
The root of the problem seems to be that `OnConnect` is called way before all upgrading logic is completed. This makes any `Emit`s in before the upgrade logic is completed basically just break everything. Hopefully I can find somewhere where the upgrade logic is done to call OnConnect instead?!

**Comment by erkie** [comment]
@googollee sorry to bother, could you help me shed some light on this issue? It seems that there is a problem with go-socket.io which causes a lot of instability: The "OnConnect" handler is called way before the socket is successfully upgraded from HTTP to Websocket. Calling `socket.Emit` while the socket is being upgraded puts the socket in deadlocked state. The solution should be to call `OnConnect` when the socket.io upgrade is completed. Where would be the best place to put this?

**Comment by googollee** [comment]
Thanks.

**Pull request merged**
