### PR TITLE
fix uuid.NewV4() in single-value context error by change to use github.com/gofrs/uuid

### PR DESCRIPTION
**Pull request by hvquy001**
Due to https://github.com/satori/go.uuid is dead and no longer maintains
https://github.com/satori/go.uuid/issues/84

I request to change to https://github.com/gofrs/uuid

### CODE REVIEW

**Comment by mrfoe7** [comment]
Hey, please look on discussion in PR https://github.com/googollee/go-socket.io/pull/437 
Do you can some refactoring into your code?

**Comment by hvquy001** [comment]
My approach a little different. I changed to use  `https://github.com/gofrs/uuid` instead of `satori/go.uuid` because it’s no longer maintain. And I just change the method to gen uuid. Nothing else. Please consider merging this request or other request asap because this error prevents us from using this module normally.

**Comment by mrfoe7** [comment]
Sorry, my comment muddle to you ((
I recommended use as a example by PR from @arrayindex-dev.
I suggest create new function `genUUID` in new file - `helpers.go` into root project path. Function will implement by `uuid.Must(uuid.NewV4()).String()` call from uuid libs

**Comment by hvquy001** [comment]
I did it. I think the name `newV4UUID` is better for understanding.

**Review by arrayindex-dev — APPROVED** [review]
Perfect! 👍👍👍👍

**Comment by mrfoe7** [comment]
Great job!

**Comment by cleverlzc** [comment]
Well done!

**Pull request merged**
