### PR TITLE
Feature: Redis broadcast adapter

### PR DESCRIPTION
**Pull request by vking34**
The adapter applies the Pub/Sub mechanism of Redis.

### CODE REVIEW

**Comment by Bioblaze** [comment]
this must be accepted, but you need to provide Examples @vking34 @googollee

**Comment by googollee** [comment]
There is a simple example in README.

The panic when connecting Redis failed is annoying. At least, `server.Adapter()` should check the connection and return err if fails.

**Comment by vking34** [comment]
> this must be accepted, but you need to provide Examples @vking34 @googollee

Thank u, the example is mentioned in the README already. Please check it. But I will add the whole sample code in the next commit.

**Comment by vking34** [comment]
> There is a simple example in README.
> 
> The panic when connecting Redis failed is annoying. At least, `server.Adapter()` should check the connection and return err if fails.

Thank u, I will fix it.

**Comment by Bioblaze** [comment]
@googollee I was talking about https://github.com/googollee/go-socket.io/tree/master/_example within there, a go-redis example. :P that is all.

**Comment by vking34** [comment]
@googollee I fixed returning an error when redis connection fails and add an example. please check it again. thank u.

**Comment by Bioblaze** [comment]
Nice

**Comment by Bioblaze** [comment]
so @vking34 this uses the same base format that socket.io-emitter uses correct?

**Comment by vking34** [comment]
@Bioblaze the same base. It just uses the redis Pub/Sub to broadcast messages between deployment instances so we can scale up horizontally.

**Comment by googollee** [comment]
@vking34 Thanks for your work. As `server.Adaptor()` is changed, it's better to update the example in README.md to handle the returning error.

**Comment by vking34** [comment]
@googollee Thank u for reminding me of it.

**Comment by ToonvanStrijp** [comment]
@googollee Any idea when this gets released? :) (@vking34 great work 🎉 !)

**Pull request merged**
