### PR TITLE
added feature to control "Access-Control-Allow-*" headers behavior

### PR DESCRIPTION
**Pull request by fujimoto**
this is the simple wrapper for https://github.com/googollee/go-engine.io/pull/17

### CODE REVIEW

**Comment by bigblind** [comment]
Looks awesome!

**Comment by fuel-shea** [comment]
I sure could use this as well.

Any idea why the checks have failed, preventing merge?

**Comment by bigblind** [comment]
The error is

    ./server.go:52: s.eio.SetAccessControl undefined (type *engineio.Server has no field or method SetAccessControl)

You can click 'details' on the travisCI Error message to view the complete output. I haven't looked into the actual code to determine the problem.

**Comment by fuel-shea** [comment]
Ah: it's waiting on https://github.com/googollee/go-engine.io/pull/17

**Comment by googollee** [comment]
@fuel-shea @bigblind I don't think go-engine.io need to do Access-Control-Allow-*. You can easily warp a handler out of go-socket.io's ServeHTTP to do that.

I don't want to introduce extra logic except of socket.io.

**Comment by googollee** [comment]
Headers like Access-Control-Allow-* should be set after checking host in request. It should not be set simply as hard code.

If wanting check the host, please wrap the ServeHTTP function and do it in wrapper.

**Pull request closed without merging**
