### PR TITLE
ADD: change signature methods in docs, test, examples

### PR DESCRIPTION
**Pull request by mrfoe7**
PR by Issue #235 and PR #237

### CODE REVIEW

**Comment by mrfoe7** [comment]
@erkie @googollee Hi, guys.
I updated #237 PR by @ardingchen
Please check PR. If it is correctly, i will merge

**Comment by erkie** [comment]
Can you also add a notice to the README about this breaking change? Something like:

```markdown
# Breaking change 2019-10-16

Changed signature of `OnError` 

From:

server.OnError(string, func(error))

To

server.OnError(string, func(Conn, error))
```

**Comment by mrfoe7** [comment]
Sure. I added list about important changed in Readme.md file.
I have idea. I propose to add new types by [issue#275](https://github.com/googollee/go-socket.io/issues/275)

**Comment by erkie** [comment]
@mrfoe7 I wonder, is this PR necessary if we're going with #275? Seems like 2 breaking changes after another, so maybe best to just jump to your idea with #275 directly?

**Pull request merged**
