### PR TITLE
V1.4

### PR DESCRIPTION
**Pull request by a2net**
**Error**
Parser is not defined or is missing

**Update path parser**
 _from_ 
"gopkg.in/googollee/go-socket.io.v1"
_to_ 
"gopkg.in/googollee/go-socket.io.v1/parser"

### CODE REVIEW

**Comment by khaydarov** [comment]
why people not accepting this pull request?

**Comment by a2net** [comment]
Maybe the developer has dumped this project, or probably have something more interesting to do as he doesn't get paid for this...

**Comment by googollee** [comment]
The patch has conflicts. Please fix them.

**Comment by niocncn** [comment]
Any updates here?

**Comment by erkie** [comment]
@a2net I wanna get this merged, but can you please update the description (or write a comment) about what you actually, what this PR fixes etc?

**Comment by a2net** [comment]
@erkie My commit was as simple as it can be.
just added the "/parser" to the import path as it was missing.

**Comment by erkie** [comment]
@a2net thanks for the clarification. Was just confused since the diff is `+10,100 −1,934` :) I guess your commits somehow got merged into a huge list of other changes?

**Comment by a2net** [comment]
@erkie Yeah that's strange.....
Not sure how someting like this happens...... Sorry if it's something I did

**Comment by erkie** [comment]
The problem was you asked to merged to master, instead of `v1.4` now it looks great :)

**Pull request merged**
