### PR TITLE
Checking for nil before calling Close

### PR DESCRIPTION
**Pull request by peterkellyonline**
Had an issue where this was panicing with a nil pointer deference occassionally and bring my service down. This check will at least stop the panics.

### CODE REVIEW

**Comment by ready4god2513** [comment]
:+1: Would like to see merged

**Comment by fuel-shea** [comment]
+1

**Comment by googollee** [comment]
Seems it's the same fix in #89?

**Comment by fuel-shea** [comment]
@googollee you're correct. It's the same fix.

**Comment by googollee** [comment]
Same as #89.

**Pull request closed without merging**
