### PR TITLE
V1.4

### PR DESCRIPTION
**Pull request by erkie**
I feel we need to merge this branch into master so it is the main basis point for moving this project forward.

@googollee you have put in a lot of great effort into this branch! The two-branched-ness of this project is causing a mental hurdle for possible future contributors but also users. Each branch has a set of issues themselves, so to avoid double work I suggest we merge this branch and get rid of 0.9 as master.

Before we do we need to understand a couple things:

- [ ] Is there anything missing for this to be production-ready?
- [ ] How do we tag the old master branch so that existing users can continue to use that code and not have to rewrite their integration
- [ ] What is needed to be done on [go-engine.io](https://github.com/googollee/go-engine.io) before this can be merged

@googollee I know that you don't have a lot of time over for this project, which is fine. I am ready to jump in and to fix any remaining _blocking_ issues or just fix the packaging side of things to get this sorted so we can leave the 0.9 version to the books of history.

### CODE REVIEW

**Comment by kunaldawn** [comment]
any updates? guys?

**Comment by erkie** [comment]
@kunaldawn This repo is lacking contributors so expect this process to take months, maybe weeks, but not days. Sorry!

**Comment by googollee** [comment]
I prefer supporting the `go mod` first then merge the branch to master. Besides the lack of features, v1.4 should be ready for prod now.

go-socket.io and go-engine.io should add `go mod` at the same time. I will try to make the change when I have time this month.

**Comment by googollee** [comment]
@erkie I updated all branches and engine.io. They are using go modules now. Do you want to update your pr to merge v1.4 to master, or open a new one?

**Comment by erkie** [comment]
@googollee awesome work! I'm happy to see the PR's merged. I guess a rebase is needed on master to get it into merge:able state though?

**Comment by googollee** [comment]
Yes. Both go-engine.io repo and this repo issues are needed rebase/merge to the latest code.

**Comment by erkie** [comment]
@googollee do you want to do that? I can try if you want/dont have time

**Comment by googollee** [comment]
I could try it now. I will report the result later.

**Comment by googollee** [comment]
@erkie Merging is done. The old master branch was v1.0 now.

**Comment by erkie** [comment]
So cool! Thanks for the work @googollee now we can start planning for the future 😀

**Pull request merged**
