### PR TITLE
Fix read closer

### PR DESCRIPTION
**Pull request by FJSDS**

### CODE REVIEW

**Comment by FJSDS** [comment]
Did you forget to Close() the ReadCloser from NextReader?

print out "Did you forget to Close() the ReadCloser from NextReader?" when client send a bad bytes .
```go
if err := json.NewDecoder(r).Decode(&values); err != nil {
	if err == io.EOF {
		err = nil
	}
	d.lastFrame.Close()
	d.lastFrame = nil
	return nil, err
}
d.lastFrame.Close()
d.lastFrame = nil
```
 so ,fix close  lastFrame when "err != nil"

**Comment by FJSDS** [comment]
> please use `defer d.lastFrame.Close()` and remove all reference `d.lastFrame.Close()` at the old version. It is fix complicated current code.

fixed

**Comment by FJSDS** [comment]
> }(); err != nil {
> 
> fix this line

fixed

**Comment by mrfoe7** [comment]
@FJSDS Is it fix this `Did you forget to Close() the ReadCloser from NextReader?` problem?

Please after PR, use gofmt by project

**Pull request closed without merging**
