### PR TITLE
Merge engine.io into socket.io

### PR DESCRIPTION
**Pull request by adrianmxb**
Discussion at #296

### CODE REVIEW

**Comment by erkie** [comment]
This is 100% the right thing to do IMO! Nice!

**Comment by adrianmxb** [comment]
Just a quick question @mrfoe7 what are you trying to do in with commit https://github.com/googollee/go-socket.io/commit/b60baee381677fc24fb8731014b9e878babb3293?

Can you post a short summary or link the related issues?
Would really help out! :-)

**Comment by mrfoe7** [comment]
@adrianmxb I wanted merge/remove engine without subdirectories, because some code in engine and socket repository duplicated. We may rollback my changes

**Comment by adrianmxb** [comment]
> @adrianmxb I wanted merge/remove engine without subdirectories, because some code in engine and socket repository duplicated. We may rollback my changes

I think that might be a good idea because it is a huge change and much more work to get it up and running. Probably better to apply your changes step-by-step.

What do you think?

**Comment by mrfoe7** [comment]
@adrianmxb I agree with you. I will revert my changes in dev branch and merge your version

**Comment by erkie** [comment]
WOOOOW

**Comment by adrianmxb** [comment]
> @adrianmxb I agree with you. I will revert my changes in dev branch and merge your version

Did you merge your version and mine togehter?
Because it seems like we have engine.io on dev branch twice now. 🤔

**Comment by mrfoe7** [comment]
@adrianmxb  yeap, In dev branch implemented `Server.Emit(clientId, event)` method by target clientId
Check it [commit](https://github.com/googollee/go-socket.io/commit/af9d40d9224f877ce2e9a52567a6a9ba49a51140)
It is experimental functional, because it is't tested by unit tests

**Comment by adrianmxb** [comment]
> @adrianmxb yeap, In dev branch implemented `Server.Emit(clientId, event)` method by target clientId
> Check it [commit](https://github.com/googollee/go-socket.io/commit/af9d40d9224f877ce2e9a52567a6a9ba49a51140)
> It is experimental functional, because it is't tested by unit tests

Yes, but why is engine.io duplicated in the branch? (See: b60baee381677fc24fb8731014b9e878babb3293)

we have Engine.io both in /connection and in the root directory now
Try to run unit tests or use the project, you will get errors left and right and it won’t compile. It’s impossible to work on this branch because it’s completely broken in its current state.

**Comment by ducquangkstn** [comment]
Can I make a PR to fix all this!
Why did you merge even this broke everything?

**Comment by erkie** [comment]
@ducquangkstn all PR's are super welcome! You should be using the tagged versions not the master branch in your app, as master is the development branch.

**Comment by mrfoe7** [comment]
@erkie @adrianmxb @ducquangkstn Today i fixed this problem. Sorry for long wait

**Comment by ducquangkstn** [comment]
@mrfoe7 : can you remove this commit then force push (by git rebase with interactive mode)

https://github.com/googollee/go-socket.io/commit/eefcf296b2418ed7a42ab68b67fdc99cea649bb9
https://github.com/googollee/go-socket.io/commit/2b1eb14117f04c728991a21dc7f2e469444338e5

It seems that some merge is error and some obsolete commits (2 years ago) still remain in dev branch.

And many commits I think from master (we can rebase dev instead of cherry pick to this branch) like this
https://github.com/googollee/go-socket.io/commit/0acee1ed6acc51deb6b9ed5688765260ec5e6d9f

This will help to speed up to process to review when we merge from dev to master

**Pull request merged**
