### PR TITLE
Move engine.io into this repo

### PR DESCRIPTION
**Pull request by erkie**
Closes https://github.com/googollee/go-socket.io/issues/296

I've verified that it works. I think 100% this is the way forward for this repo. We need to simplify the stack so we can work faster. Having 2 dependencies is a pain with `go.mod` etc and confusing for new contributors. 

If someone relies on go-engine.io only they can still just import /engine from this repo, so nothing of value is lost.

### CODE REVIEW

**Comment by adrianmxb** [comment]
I'll have a look after work.

**Comment by erkie** [comment]
@adrianmxb awesome! Changed my approach to use git subtree add like I think you did in a previous version of this. Preserves history too which is nice! Also, my original PR had the engineio stuff under `engine/` directory. Updated that to be `engineio/` so package name matches directory.

Updated the README as well.

**Comment by mrfoe7** [comment]
Hey, @erkie 
Why we need merge double projects? I don't understand motivation about it. We need correctly separate layers and interfaces between engine and server API

**Comment by adrianmxb** [comment]
I think #296 explains it pretty well and I thought we all were on the same page about merging the projects, no?

@erkie looks good btw. 👍

**Review by adrianmxb — APPROVED** [review]

**Comment by erkie** [comment]
@adrianmxb @mrfoe7 the main goal is like googollee mentioned in the issue to reduce complexity. There is no need to have two separate repos, so why should we? It simplifies managing the project as well since it's all collected in one repository. Now we have issues in this repo, but also go-engine.io. It simplifies contributing since we only need to change 1 repo. Releases will be easier since we don't have to remember to update dependencies whenever a change in go-engine.io happens. If you want to use the engine code separately, it's still possible, but it seems like such a minor use case of this library that we shouldn't optimise for it.

**Pull request merged**
